### ISSUE TITLE
HTTPClient(Protocol)の別リポジトリ(パッケージ)化について

### ISSUE THREAD

**Issue by zunda-pixel** [sidepelican/D1Kit#5]
HTTPClient(Protocol)は、どのAPIクライアント系のライブラリでも現在必須と感じています。
各ライブラリで実装して名前の衝突することを避けるために、別リポジトリに分けて共通化をできないでしょうか？

**Comment by sidepelican** [comment]
名前空間はパッケージによって分離されているため多少広い名前を使っていても少ししか困らないと思っているのですが、具体的に名前が衝突することにどのような課題を感じているのでしょうか？

> 別リポジトリに分けて共通化

これはAppleなどの大きめのベンダーからそのようなライブラリが出ていれば乗っかりたいですが（`swift-http-types`に乗っかってるのはそうですし）、現状個人が野良でやる分には普及が難しいと思っています

**Comment by zunda-pixel** [comment]
パッケージごとの名前空間があると思っていたのですが、複数のパッケージで同じようなHTTPClientを定義した際にエラーが出てしまっていました。再調査してみます...
Appleが作るには小さすぎるし、個人でやるには広すぎると自分も感じています。

**Comment by sidepelican** [comment]
基本的に衝突するようなケースでは`D1Kit.HTTPClientProtocol`とパッケージ名を明示して利用すれば問題を回避できると思います。
そのほか、`import struct D1Kit.D1Database`のような部分的なimport方法もあります
回避が難しいケースがあれば教えてください。

**Comment by zunda-pixel** [comment]
HTTPClientという`target`をLibrary1とLibrary2が持っていて、それら2つをdependenciesに追加するとtarget名がぶつかってしまいエラーになるという問題でした。

```
multiple packages ('library1', 'library2') declare targets with a conflicting name: 'HTTPClient’; target names need to be unique across the package graph
```

こちら`moduleAliases`を使えば解決可能ということがわかったのですが、こちらを一つのアプリやサーバーでいくつものAPIクライアント系ライブラリを入れていると、名前解決が冗長になってしまうというのが問題でした。

```swift
.target(
  name: "Library3",
  dependencies: [
    .product(name: "Library1", package: "Library1", moduleAliases: ["HTTPClient": "HTTPClient1"]),
    .product(name: "Library2", package: "Library2", moduleAliases: ["HTTPClient": "HTTPClient2"])
  ]
),
```

**Comment by sidepelican** [comment]
今の所名前衝突に関する回避の難しい問題はなさそうですし、
プロトコルの共通化は現実的でなく実施予定がないため閉じます。

**Comment by zunda-pixel** [comment]
HTTPClientの部分を個人でパッケージ化しても問題ないでしょうか？
また`swift-http-types`へのHTTPClientの追加に関するプルリクを行っても問題ないでしょうか？(マージされる可能性は低いと思うのですが)

**Comment by sidepelican** [comment]
個人でパッケージを作成する分にはもちろん構いませんが、
元々の普及率の課題が解決されていない限りD1Kitにそれを使うPRはマージできません。

----

`swift-http-types`に投げかけてみるのも良い試みだと思いますが、私は難しいと思っています。
というのも、HTTPリクエストのBodyに使う型の定義が難しいからです。

主な候補は3つだと思っているのですが、どれも課題があります。

- `Data`
- `ByteBuffer`
- `[Int8]`

`Data`はFoundationに定義されていて、普段Appleプラットフォームで開発していると馴染みがないかもしれませんが、Foundationを利用したくないケースもあり得ます。実際、`swift-http-types`ではFoundationに依存した部分は別ターゲットになっています。
`ByteBuffer`はSwiftNIOに実装されていて、Foundationよりさらに汎用的と言えません。
`[Int8]`は標準ライブラリだけで利用できますが、これは低機能すぎます。プリミティブすぎてパフォーマンス上他のものより劣る可能性があるため利用は難しいでしょう。

いずれにせよ、アプリケーションで主につかっているバイト列型からBody型の変換が必要になると途端に使いづらくなってしまうので、変換を不要にするためにはそもそもBody型を定義しない、という選択になると思います。
Swift標準ライブラリに高パフォーマンスかつ汎用性の高いバイト列型が実装されれば話が変わりそうですが、いまのところそのような話はなさそうです。

もちろんこれが理由とは限らないので、一度投げかけてみるのは良いと思います。

**Comment by zunda-pixel** [comment]
ありがとうございます。一度投げかけてみます。

Bodyの問題は前に少し見たのですが、難しすぎてわかりませんでした...
